# Generated by Django 5.1.4 on 2025-05-20 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='')),
                ('name', models.CharField(max_length=80)),
                ('desc', models.TextField()),
                ('price', models.IntegerField()),
                ('offer', models.BooleanField()),
            ],
        ),
    ]
